apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: pvvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: ckad-1
    readOnly: false