apiVersion: v1
kind: Pod
metadata:
  name: sample-env
  lables:
    app: sample-app
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      env:
        - name: MAX_CONNECTION
          value: "100"
        - name: TZ
          value: Asia/Tokyo
        - name: K8S_NODE # Podに関する情報を参照しつつ環境変数に設定
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CPU_REQUESTS
          valueFrom:
            resourceFieldRef:
              containerName: nginx-container
              resouce: requests.cpu
        - name: CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: nginx-container
              resouce: limits.cpu
