apiVersion: v1
kind: LimitRange
metadata:
  name: sample-limitrange-pvc
  namespace: default
spec:
  limits:
    - type: PesistentVolumeClaim
      max:
        storage: 10Gi
      min:
        storage: 4Gi
