apiVersion: v1
kind: ResourceQuota
metadata:
  name: samlple-resource-count-new
  namespace: default
spec:
  hard:
    # 作成可能なリソースの数
    count/persistentvolumeclaims: "10"
    count/services: "10"
    count/secrets: "10"
    count/configmaps: "10"
    count/deployments.apps: "10"
    count/replicasets.apps: "10"
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"