apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    # ビルドしたDockerイメージの保存先とイメージ名
    - imageName: yumatsud/skaffold-sample
#  local:
#    skipPush: true
deploy:
  kubectl:
    manifests:
      # 適応するマニフェストのファイル名
      - skaffold-*
profiles:
  # ローカルビルドでDockerイメージのPushをskip
  # Docker for mac環境に開発用のマニフェストを使用するプロファイル
  - name: devProfile
    build:
      local:
        skipPush: true
    deploy:
      kubectl:
        flags:
          global:
            # kubectl実行時に--contextオプションを渡して
            # Docker for macの環境を使う
            - --context=docker-for-desktop
        manifests:
          - dev-skaffold-*