apiVersion: v1
kind: Service
metadata:
  name: skaffold-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: "http-port"
      protocol: "TCP"
      targetPort: 8080
  selector:
    app: skaffold-sample