apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
data:
  thread: 6
  connection.max: "100"
  connection.min: "10"
  sample.properies: | # valueが複数行にわたる場合はこれを使う
    propery.1=value-1
    propery.2=value-2
    propery.3=value-3
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid
