apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    type: webserver
spec:
  containers:
    - name: webcont
      image: nginx:1.13
      ports:
        - containerPort: 80
    - name: fdlogger
      image: fluent/fluentd

